version: '3.8'

services:
  vault:
    container_name: vault
    image: vault-local-fs
    hostname: vault
    ports:
      - 443:8200
    environment:
      - VAULT_CACERT=/opt/vault/tls/vault-ca.pem
      - VAULT_TLSCERT=/opt/vault/tls/vault-cert.pem
      - VAULT_TLSKEY=/opt/vault/tls/vault-key.pem
      - VAULT_ADDR=https://vault:8200
      - VAULT_API_ADDR=https://vault:8200
      - VAULT_CONFIG_DIR=/vault/config
    command: server -config=/vault/config/config.json
    volumes:
      - ./tls/ca-chain.pem:/opt/vault/tls/vault-ca.pem
      - ./tls/client-chain.pem:/opt/vault/tls/vault-cert.pem
      - ./tls/vault.key.pem:/opt/vault/tls/vault-key.pem
      - ./config/vault-config.json:/vault/config/config.json
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - vault